// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for suggesting content improvements using AI.
 *
 * - suggestContentImprovements - A function that takes content and a target keyword as input and returns AI-powered suggestions for improvement.
 * - SuggestContentImprovementsInput - The input type for the suggestContentImprovements function.
 * - SuggestContentImprovementsOutput - The return type for the suggestContentImprovements function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestContentImprovementsInputSchema = z.object({
  content: z.string().describe('The current content to be analyzed.'),
  targetKeyword: z.string().describe('The target keyword for SEO optimization.'),
});
export type SuggestContentImprovementsInput = z.infer<typeof SuggestContentImprovementsInputSchema>;

const SuggestContentImprovementsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('A list of AI-powered suggestions for improving the content.'),
});
export type SuggestContentImprovementsOutput = z.infer<typeof SuggestContentImprovementsOutputSchema>;

export async function suggestContentImprovements(input: SuggestContentImprovementsInput): Promise<SuggestContentImprovementsOutput> {
  return suggestContentImprovementsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestContentImprovementsPrompt',
  input: {schema: SuggestContentImprovementsInputSchema},
  output: {schema: SuggestContentImprovementsOutputSchema},
  prompt: `You are an SEO expert. Analyze the following content and provide suggestions to improve it for the target keyword.

Content: {{{content}}}
Target Keyword: {{{targetKeyword}}}

Suggestions (in array format):
`,
});

const suggestContentImprovementsFlow = ai.defineFlow(
  {
    name: 'suggestContentImprovementsFlow',
    inputSchema: SuggestContentImprovementsInputSchema,
    outputSchema: SuggestContentImprovementsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
